# Generated by Django 4.2.2 on 2024-05-08 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Token'),
        ),
    ]
