# Generated by Django 5.0.3 on 2024-04-25 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0003_alter_product_options_product_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.CharField(max_length=100, unique=True, verbose_name='Человекопонятный URL'),
        ),
    ]
