# Generated by Django 5.0.3 on 2024-04-28 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0004_alter_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='product',
            name='views',
        ),
    ]
