# Generated by Django 5.0.3 on 2024-04-30 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0007_alter_product_options_alter_version_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='is_current_version',
            field=models.BooleanField(default=False, verbose_name='Признак текущей версии'),
        ),
    ]
