# Generated by Django 5.0.3 on 2024-05-07 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0008_alter_version_is_current_version'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='version',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current_version', True)), fields=('product',), name='only_one_active_version_for_product'),
        ),
    ]
